import json
import smtplib
import threading
from dataclasses import dataclass
from email.message import EmailMessage
from pathlib import Path
from typing import Optional


CONFIG_PATH = Path(__file__).with_name("config.json")


@dataclass
class EmailConfig:
    smtp_server: str
    smtp_port: int
    use_tls: bool
    sender_email: str
    sender_password: str
    recipient_email: str

    @staticmethod
    def from_dict(d: dict) -> "EmailConfig":
        return EmailConfig(
            smtp_server=d["smtp_server"],
            smtp_port=int(d["smtp_port"]),
            use_tls=bool(d.get("use_tls", True)),
            sender_email=d["sender_email"],
            sender_password=d["sender_password"],
            recipient_email=d["recipient_email"],
        )


def load_email_config() -> Optional[EmailConfig]:
    if not CONFIG_PATH.exists():
        return None
    with open(CONFIG_PATH, "r", encoding="utf-8") as f:
        data = json.load(f)
    if "email" not in data:
        return None
    return EmailConfig.from_dict(data["email"])


def _send_key_email_sync(config: EmailConfig, password: str) -> None:
    msg = EmailMessage()
    msg["Subject"] = "New Encryption Key (Time-based Rotation)"
    msg["From"] = config.sender_email
    msg["To"] = config.recipient_email

    body = (
        "A new encryption password has been generated by the Advanced File Protection System.\n\n"
        f"Password: {password}\n"
        "Note: Treat this password as sensitive information. Do not share it with unauthorized users."
    )
    msg.set_content(body)

    try:
        if config.use_tls:
            with smtplib.SMTP(config.smtp_server, config.smtp_port) as server:
                server.starttls()
                server.login(config.sender_email, config.sender_password)
                server.send_message(msg)
        else:
            with smtplib.SMTP(config.smtp_server, config.smtp_port) as server:
                server.login(config.sender_email, config.sender_password)
                server.send_message(msg)
    except smtplib.SMTPAuthenticationError as e:
        # Authentication failure (e.g., wrong password or provider blocking login)
        print("[Email] Authentication failed while sending key email:", e)
    except Exception as e:
        # Any other email-related error
        print("[Email] Failed to send key email:", e)


def send_key_email_async(config: EmailConfig, password: str) -> None:
    """Send the key email in a background thread so that the GUI does not block."""

    thread = threading.Thread(
        target=_send_key_email_sync,
        args=(config, password),
        daemon=True,
    )
    thread.start()
